export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',

  STRAVA_NOT_CONNECTED: 'STRAVA_NOT_CONNECTED',
  STRAVA_TOKEN_EXPIRED: 'STRAVA_TOKEN_EXPIRED',
  STRAVA_RATE_LIMITED: 'STRAVA_RATE_LIMITED',
  STRAVA_ACCOUNT_ALREADY_LINKED: 'STRAVA_ACCOUNT_ALREADY_LINKED',
  STRAVA_FETCH_FAILED: 'STRAVA_FETCH_FAILED',
  STRAVA_IMPORT_FAILED: 'STRAVA_IMPORT_FAILED',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_VALIDATION_FAILED: 'SESSION_VALIDATION_FAILED',
  SESSION_SAVE_FAILED: 'SESSION_SAVE_FAILED',
  SESSION_DELETE_FAILED: 'SESSION_DELETE_FAILED',

  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_SERVER_ERROR: 'NETWORK_SERVER_ERROR',

  VALIDATION_FAILED: 'VALIDATION_FAILED',

  IMPORT_INVALID_FORMAT: 'IMPORT_INVALID_FORMAT',
  IMPORT_PARSE_ERROR: 'IMPORT_PARSE_ERROR',
  IMPORT_NO_DATA: 'IMPORT_NO_DATA',

  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export type ErrorSeverity = 'critical' | 'error' | 'warning' | 'info';

export interface ErrorAction {
  label: string;
  handler: () => void;
}

export interface AppErrorOptions {
  code: ErrorCode;
  message?: string;
  severity?: ErrorSeverity;
  isRecoverable?: boolean;
  action?: ErrorAction;
  statusCode?: number;
  details?: unknown;
}
